### PR TITLE
Feature/view identification

### PR DESCRIPTION
**Pull request by hw4m**
Hey, nice work you did on this thing. I did how ever find a bug when using the colorizer method, but came up with a nice solution. Hope you can use it.

### CODE REVIEW

**Comment by ligi** [comment]
What was the bug you where stumbling upon?

**Comment by hw4m** [comment]
It's been a while so I cannot remember the specifics, but I has a specific view (or subclass of a view) that wasn't being correctly identified - and therefore didn't get tinted as expected.

**Comment by ligi** [comment]
Thanks for the fast answer!

**Comment by powerpoint45** [comment]
This looks very good. Very neat and clean. Most importantly works well. Thank you for your contribution. I have merged your changes.

**Pull request merged**
